#!/usr/bin/env bash

INPUT_BASE_DIR="$HOME/raw50"
OUTPUT_BASE_DIR="$HOME/plots50"

for INPUT_DIR in "$INPUT_BASE_DIR"/*/*; do

    VARIANT=$(basename "$INPUT_DIR")
    ANALYSIS=$(basename "$(dirname "$INPUT_DIR")")
    OUTPUT_DIR="$OUTPUT_BASE_DIR/$ANALYSIS/$VARIANT"
    mkdir -p "$OUTPUT_DIR"

    # du
    awk '{print $1}' "$INPUT_DIR"/minio_du/* > "$OUTPUT_DIR"/du

    # ls
    awk '{print $2}' "$INPUT_DIR"/minio_du/* > "$OUTPUT_DIR"/ls

    # hms
    du "$INPUT_DIR"/hms/* | cut -f 1 > "$OUTPUT_DIR"/hms

    # trace
    wc -l "$INPUT_DIR"/trace/* | awk '{print $1}' > "$OUTPUT_DIR"/trace

    # runtime
    paste <(grep -h SparkListenerSQLExecutionStart "$INPUT_DIR"/runtime/* | jq --slurp 'map(select(.executionId == 1) | .time) | .[]') <(grep -h SparkListenerSQLExecutionEnd "$INPUT_DIR"/runtime/* | jq --slurp 'map(select(.executionId == 1) | .time) | .[]') | awk '{print $2 - $1}' > "$OUTPUT_DIR"/runtime

    # sar
    sadf -d "$INPUT_DIR"/sar/benchmark.sar -- -u > "$OUTPUT_DIR"/sar_cpu
    sadf -d "$INPUT_DIR"/sar/benchmark.sar -- -r > "$OUTPUT_DIR"/sar_ram
    sadf -d "$INPUT_DIR"/sar/benchmark.sar -- -F --fs=/dev/mapper/crypthome > "$OUTPUT_DIR"/sar_fs
    sadf -d "$INPUT_DIR"/sar/benchmark.sar -- -d --dev=nvme0n1p6 > "$OUTPUT_DIR"/sar_disk
    sadf -d "$INPUT_DIR"/sar/benchmark.sar -- -F --fs=/dev/mapper/crypthome > "$OUTPUT_DIR"/sar_fs

done
