#!/usr/bin/env python

import sys

if len(sys.argv) < 3:
    print("Usage: ./datagen.py TABLE_NAME NUM_VALUES")
    sys.exit(1)

table_name = sys.argv[1]
num_values = int(sys.argv[2])

print(f"""INSERT INTO {table_name} (key)
VALUES {', '.join('(' + str(val) + ')' for val in range(1, num_values + 1))};""")
