#!/usr/bin/env bash

set -e

NUM_REPS=50

SCHEMA_NAME=many_deletes
BUCKET_NAME=many-deletes

OUTPUT_BASE_DIR=results
mkdir -p "$OUTPUT_BASE_DIR"

mcli rb --force "minio/$BUCKET_NAME"

for CATALOG in iceberg delta; do

    OUTPUT_DIR="$OUTPUT_BASE_DIR/$CATALOG"
    if [[ -d "$OUTPUT_DIR" ]]; then
        echo "$OUTPUT_DIR already exists"
        exit 1
    fi

    mkdir -p "$OUTPUT_DIR"/{sar,trace,runtime,minio_du,minio_ls,hms}

    mcli mb "minio/$BUCKET_NAME"

    $TRINO_HOME/bin/trino --catalog "$CATALOG" --execute 'DROP SCHEMA IF EXISTS $SCHEMA_NAME CASCADE;'
    $TRINO_HOME/bin/trino --catalog "$CATALOG" --execute "CREATE SCHEMA IF NOT EXISTS $CATALOG.$SCHEMA_NAME WITH (location = 's3a://$BUCKET_NAME/');"

    # Relies on hive.storage-format, iceberg.file-format, and *.compression-codec being set
    $TRINO_HOME/bin/trino --catalog "$CATALOG" --schema "$SCHEMA_NAME" --execute 'CREATE TABLE data (key INT);'
    $TRINO_HOME/bin/trino --catalog "$CATALOG" --schema "$SCHEMA_NAME" --file inserts.sql

    # Start sar monitoring
    sar -o "$OUTPUT_DIR/sar/benchmark.sar" -u -r -d --dev=nvme0n1 -F --fs=/dev/mapper/cryptroot 1 &> /dev/null &
    SAR_PID=$!

    sleep 3

    for REP in $(seq -w 1 "$NUM_REPS"); do

        $TRINO_HOME/bin/trino --catalog "$CATALOG" --schema "$SCHEMA_NAME" --execute "DELETE FROM data WHERE key = $((10#$REP));" &> /dev/null

        QUERY_ID="${CATALOG}_${REP}_$(openssl rand -hex 4)"

        # Start background tracing
        mcli admin trace minio > "$OUTPUT_DIR/trace/$REP" &
        TRACE_PID=$!

        # Perform query
        $TRINO_HOME/bin/trino --source "$QUERY_ID" --catalog "$CATALOG" --schema "$SCHEMA_NAME" --execute 'SELECT * FROM data;' --output-format NULL

        # Stop background tracing
        kill -SIGINT $TRACE_PID

        # Collect runtime
        $TRINO_HOME/bin/trino --execute "SELECT CAST(TO_UNIXTIME(started) AS INT), TO_MILLISECONDS(\"end\" - started) FROM system.runtime.queries WHERE source = '$QUERY_ID';" --output-format CSV_UNQUOTED 2>/dev/null > "$OUTPUT_DIR/runtime/$REP"

        # Collect MinIO bucket size and number of objects
        s3cmd du "s3://$BUCKET_NAME" > "$OUTPUT_DIR/minio_du/$REP"

        # Collect HMS SQL dump and size
        sudo -u postgres pg_dump hms > "$OUTPUT_DIR/hms/$REP"

        echo "$CATALOG: $REP / $NUM_REPS"

    done

    # Stop sar monitoring
    kill -SIGINT $SAR_PID

    $TRINO_HOME/bin/trino --catalog "$CATALOG" --execute 'DROP SCHEMA $SCHEMA_NAME CASCADE;'

    mcli rb --force "minio/$BUCKET_NAME"

done

# Make a copy of the connector config
mkdir -p "$OUTPUT_BASE_DIR/conf"
cp $TRINO_HOME/etc/catalog/*.properties "$OUTPUT_BASE_DIR/conf/"
